/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int APAR = 8;
  /** RegularExpression Id. */
  int FPAR = 9;
  /** RegularExpression Id. */
  int VOID = 10;
  /** RegularExpression Id. */
  int FLOATCHAVE = 11;
  /** RegularExpression Id. */
  int BOOL = 12;
  /** RegularExpression Id. */
  int ELCHAVE = 13;
  /** RegularExpression Id. */
  int ATTCHAVE = 14;
  /** RegularExpression Id. */
  int LET = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int DO = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int DEF = 19;
  /** RegularExpression Id. */
  int READ = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int PRINT = 22;
  /** RegularExpression Id. */
  int SUM = 23;
  /** RegularExpression Id. */
  int SUB = 24;
  /** RegularExpression Id. */
  int MULT = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int SYMHIGHER = 29;
  /** RegularExpression Id. */
  int SYMLOWER = 30;
  /** RegularExpression Id. */
  int EQUAL = 31;
  /** RegularExpression Id. */
  int SEP = 32;
  /** RegularExpression Id. */
  int TRUE = 33;
  /** RegularExpression Id. */
  int FALSE = 34;
  /** RegularExpression Id. */
  int TOKEN_NUM = 35;
  /** RegularExpression Id. */
  int TOKEN_ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"void\"",
    "\"float\"",
    "\"bool\"",
    "\";\"",
    "\":=\"",
    "\"let\"",
    "\"while\"",
    "\"do\"",
    "\"if\"",
    "\"def\"",
    "\"readIO\"",
    "\"return\"",
    "\"printIO\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\",\"",
    "\"true\"",
    "\"false\"",
    "<TOKEN_NUM>",
    "<TOKEN_ID>",
  };

}
